// src/routes/media/[...file]/+page.server.ts
import fs from 'node:fs/promises';
import path from 'node:path';
import { error } from '@sveltejs/kit';
// This file is generated by SvelteKit automatically
import type { PageServerLoad } from './$types'; 

export const load: PageServerLoad = async ({ params }) => {
    // Now params.file is recognized as a string
    const fileParam = params.file; 
    
    const fullPath = path.resolve('portals', fileParam);
    
    try {
        const stats = await fs.stat(fullPath);
        return {
            name: path.basename(fileParam),
            dir: path.dirname(fileParam),
            size: (stats.size / (1024 * 1024)).toFixed(2) + ' MB',
            lastModified: stats.mtime
        };
    } catch (err) {
        console.error(err)
        throw error(404, 'A portal does not yet exist to this location');
    }
};